### ISSUE TITLE
The same problem 

### ISSUE THREAD

**Issue by Imaginev2** [rimuy/weebcord#11]
This time happened with Lucy. idk why the sotftware isn't working, tell me something to check and i'll do it @Kevinwkz .
![image](https://user-images.githubusercontent.com/73681316/97811821-0069f100-1c4b-11eb-9d47-a470d15f82f8.png)
![image](https://user-images.githubusercontent.com/73681316/97181831-0f50a380-1c4b-11eb-942a-9509dd1c160c.png)

**Comment by rimuy** [comment]
@AwEzBro Updated, check out [releases](https://github.com/Kevinwkz/weebcord/releases/tag/1.1.4)
