### ISSUE TITLE
Still not working... (oof)

### ISSUE THREAD

**Issue by Imaginev2** [rimuy/weebcord#12]
This time happened with Zero Two (Lmao) 
![image](https://user-images.githubusercontent.com/73681316/97902993-65395000-1d0c-11eb-91ec-f6643d3ddfef.png)
![image](https://user-images.githubusercontent.com/73681316/97903044-72eed580-1d0c-11eb-8a54-ac2e94d2ee3d.png)
@Kevinwkz if u want me to check something of the logs tell me. (i don't know anything of coding so i can't help you in that way, sorry.)

**Comment by rimuy** [comment]
@AwEzBro You can send another screenshot of the console to me. If nothing shows up, check the C:\Users\<yourUser>\AppData\Local\Weebcord\lists directory and screenshot what is in there.

**Comment by Imaginev2** [comment]
This is what it shows 
![image](https://user-images.githubusercontent.com/73681316/97904021-eba26180-1d0d-11eb-9267-67442a6c3587.png)
![image](https://user-images.githubusercontent.com/73681316/97904070-fa891400-1d0d-11eb-957c-5ef8276660f2.png)

**Comment by rimuy** [comment]
Finally fixed, gotta publish it in a few minutes. This programming language can be annoying sometimes ...

**Comment by rimuy** [comment]
@AwEzBro Seems like everything is working fine here
![image](https://user-images.githubusercontent.com/46044567/97916321-97a97400-1d31-11eb-93a9-812ebaac86a1.png)
![image](https://user-images.githubusercontent.com/46044567/97916564-ec4cef00-1d31-11eb-8c68-d37d68d3e36b.png)

**Comment by AwEzBro** [comment]
I'll test it and i'll see, ¡thx for the effort in the software! @Kevinwkz

**Comment by Imaginev2** [comment]
> @AwEzBro Seems like everything is working fine here
> ![image](https://user-images.githubusercontent.com/46044567/97916321-97a97400-1d31-11eb-93a9-812ebaac86a1.png)
> ![image](https://user-images.githubusercontent.com/46044567/97916564-ec4cef00-1d31-11eb-8c68-d37d68d3e36b.png)
I'll test it, thx for the effort in the software @Kevinwkz !!

**Comment by Imaginev2** [comment]
All working very good here!!! Tysm for the effort in the software @Kevinwkz !!!
![image](https://user-images.githubusercontent.com/73681316/97951404-128d8180-1d68-11eb-81c1-cba79cc2b9ab.png)
