### ISSUE TITLE
Mudae server

### ISSUE THREAD

**Issue by Fanreza** [rimuy/weebcord#15]
Previously I apologized if this question was disturbing, can this application be used on all servers that have mudae bot?, because here I was not asked to enter the server id,and earlier I received a notification that one of my waifu was claimed, but when I checked on my server, the waifu was still not claimed by anyone
![Capture](https://user-images.githubusercontent.com/57042204/98138548-cd975580-1ef5-11eb-8999-93fbdf0957f9.PNG)

**Comment by Fanreza** [comment]
and I also apologize if my English is bad, because here I use google translate

**Comment by rimuy** [comment]
@Fanreza Yeah, it collects from all the servers you are in, the filter feature has not been developed yet.

**Comment by Fanreza** [comment]
> 
> 
> @Fanreza Yeah, it collects from all the servers you are in, the filter feature has not been developed yet.

By the way, does this application support every reaction emoji? And if we have no claims, will this application still react to these emojis?, and is it true that this is an auto claim application? or just monitoring? because just now one of my wish lists came out, but this application doesn't claim

**Comment by rimuy** [comment]
It does support all the reaction emojis mudae uses; If you have no claims it will still try a claim since usually people's waifu lists aren't that big, although that's a good feature request; It is explicit in the documentation that you need to upload a .txt file with all the character names to set it up, not just by using your server wishlist (which is kinda limited). Take in consideration that this is the 1.x.x version of the application.

**Comment by Fanreza** [comment]
yes I have made the .txt file before and enter it in settings.  
![Capture](https://user-images.githubusercontent.com/57042204/98153115-494cce80-1f05-11eb-9c50-4a328e1b7314.PNG)
![Capture](https://user-images.githubusercontent.com/57042204/98153232-6f726e80-1f05-11eb-9718-a883d870bf1e.PNG)



before I didn't have a claim, and I think that's what caused my wish list not to be reacted, but that's fine, by the way, does this application still work even though I don't open discord?

**Comment by rimuy** [comment]
You might have downloaded an outdated version then, if not, that's a new issue. I am sure I already fixed it but check out what version you are currently in. And yes it works even with discord closed, that's what you use your token for!

**Comment by Fanreza** [comment]
I opened the version file and got the version, maybe there was a little error that I did, after all this is just the first try so it's okay
![Capture](https://user-images.githubusercontent.com/57042204/98154441-5cf93480-1f07-11eb-87eb-68787e57a3cf.PNG)

**Comment by rimuy** [comment]
By version I meant the software's release version registered on github:

https://github.com/Kevinwkz/weebcord/releases
![image](https://user-images.githubusercontent.com/46044567/98154833-23e3a480-1eb4-11eb-8b67-8b73aafc9e83.png)

**Comment by Fanreza** [comment]
I previously downloaded it, but never mind I'll try again.
This is a good project I think, because the difference is using the application, thanks in advance

**Comment by Fanreza** [comment]
My second attempt ended badly, the waifu that I listed in the application was not automatically claimed
![Capture](https://user-images.githubusercontent.com/57042204/98164323-aef58680-1f16-11eb-9238-f247e25a233c.PNG)
the message appears in the application, but does not claim


and this is my third try, the application still doesn't claim
![Capture](https://user-images.githubusercontent.com/57042204/98164678-3b07ae00-1f17-11eb-86a5-23e3a0cfdff1.PNG)

**Comment by rimuy** [comment]
New thing, so it seems mudae developers added the new colored hearts to their emoji collection.
https://emojipedia.org/hearts/

The software's current emoji list is:
![image](https://user-images.githubusercontent.com/46044567/98165301-68773c00-1ec4-11eb-85ed-fd4a311638c0.png)

It was working very well for everyone else, that's why I haven't added them. Thank you for the information, I gotta add it soon. Yet it's still odd that all the reaction emojis from your mudae didn't happen to be one of the list, lol

**Comment by Fanreza** [comment]
hahaha,maybe this is the reason why this application does not claim on my server, on my server the emojis used are: broken_heart: and: blue_heart:, the problem is solved.By the way, can I manually input emoji in the application? If possible, which script can I edit

**Comment by rimuy** [comment]
@Fanreza It's the "emojis" array located in https://github.com/Kevinwkz/weebcord/blob/master/src/bots/mudae.json

Would be nice if you also added the other colored hearts so that we can end this issue for anyone else. Will merge your PR and make a release once I get home. Ty.

**Comment by Fanreza** [comment]
I have entered 2 emojis on my server and rebuilt the application and it worked
