### ISSUE TITLE
Grey Screen

### ISSUE THREAD

**Issue by GabunoDragunora** [rimuy/weebcord#3]
when i put my token after a little time the screen gets grey
![Screenshot_4](https://user-images.githubusercontent.com/73045711/97105194-ef900d00-1697-11eb-8466-49b541588193.png)

**Comment by Imaginev2** [comment]
Same thing happens to me

**Comment by Imaginev2** [comment]
@Kevinwkz Do you know how to fix it? if you know, pls tell us.

**Comment by rimuy** [comment]
@AwEzBro @GabunoDragunora Let me know if this still persists, I fixed the path require method, which could be the error since it couldn't find the user's app root directory.

**Comment by GabunoDragunora** [comment]
@Kevinwkz soo, in my case i downloaded the new vesion, and i executede them in my desktop and the gray screen continues, dosen't load anything, so i tried to put into the discord root folder and the same thing also i tried to execute the exe in administrator mode and still nothing happens, what i have to do ?

**Comment by GabunoDragunora** [comment]
@Kevinwkz good job, is working 100%, thank you dude !
