### ISSUE TITLE
Doesn't detect rolls from another or idk what happened (?)

### ISSUE THREAD

**Issue by Imaginev2** [rimuy/weebcord#7]
I checked the waifu list in a while and there was Tanya Degurechaff but when she appeared, it didn't claim her, idk why but ehm, is this a bug? 

![image](https://user-images.githubusercontent.com/73681316/97769757-a4448700-1afb-11eb-90bf-62d26c3dc5d1.png)
![image](https://user-images.githubusercontent.com/73681316/97769774-c2aa8280-1afb-11eb-85aa-ddb4df8b250c.png)

Can you check it @Kevinwkz pls?

**Comment by rimuy** [comment]
Probabily just another file directory missing, will take a look
