### ISSUE TITLE
Still not working (?

### ISSUE THREAD

**Issue by Imaginev2** [rimuy/weebcord#9]
It still not working on claiming (sadly), Akame appeared and i didn't get it, my friend got it in the sv. (lmao), btw i have the lastest release 
@Kevinwkz I'm sorry if i'm bothering you too much with the pings...
![image](https://user-images.githubusercontent.com/73681316/97793622-6fe4cf80-1bbc-11eb-80db-e7f70ef37af6.png)
![image](https://user-images.githubusercontent.com/73681316/97793633-89861700-1bbc-11eb-9582-4e36e886d1cc.png)

**Comment by rimuy** [comment]
Don't worry! keep reporting the issues you get with the software so it can be finally stable, apparently all the previous errors had to do with electron (the framework used), but this time it may not be that. Last version I enabled the browser console, try using it by pressing F12 or Ctrl+Shift+I to debug and then screenshot the result, so it can be easier to identify what is going on there.

**Comment by Imaginev2** [comment]
I will still using at the moment and check it again when a top 500 appear cause i accidentally closed it (lmao) meanwhile browsing in the browser console, btw i saw something about "claim rank" i think it's cause i didn't have enabled the "claim rank in rolls" and only "like rolls" i will enable them and then i'll tell you if this still happening @Kevinwkz

**Comment by Imaginev2** [comment]
Btw, always when i re-open the software it appears "disconnected" does it means something? because i needed to put the token again and remove the acc to make it "connected" 
![image](https://user-images.githubusercontent.com/73681316/97793961-467a7280-1bc1-11eb-93d1-c7879bd22310.png)

**Comment by rimuy** [comment]
It auto disconnects all the instances if you close the application, also you don't need to reload the token again and over again, you can click the account tab twice to connect/disconnect. I guess it still needs some documentation, mb. Also where did you see the "claim rank" thing, I don't think that's a feature I've added yet.

**Comment by Imaginev2** [comment]
It is an assimilation what I did of "claim rank" since I saw it out of the corner of my eye, sorry if i make you confused

**Comment by Imaginev2** [comment]
It still happening, now with Yui Hirasawa (lmao) 
![image](https://user-images.githubusercontent.com/73681316/97794805-72e7bc00-1bcc-11eb-9c22-6cdf784fe2a7.png)
![image](https://user-images.githubusercontent.com/73681316/97794810-8d219a00-1bcc-11eb-987f-fec73505ca2e.png)
btw what or where should i search in the browser console @Kevinwkz i have it open right now

**Comment by Imaginev2** [comment]
@Kevinwkz this is what it says when i opened the browser console 
![image](https://user-images.githubusercontent.com/73681316/97794854-310b4580-1bcd-11eb-9234-352cf6553695.png)

**Comment by rimuy** [comment]
Alright thank you, looks like it was just another path require error, now I shall use the path library for all the module requires. I will make a pull request and release the fix version. That's it for today, please open another issue if the problem still persists on other features of the software and I will take a look once I wake up.
